In [1]:
import numpy as np
import pandas as pd

In [2]:
m1=pd.read_csv('3.2.1PandaMovies.csv')
m1.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [3]:
m1.shape

(979, 6)

In [4]:
m1.dtypes

star_rating       float64
title              object
content_rating     object
genre              object
duration            int64
actors_list        object
dtype: object

In [5]:
m1.columns

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [6]:
m1.content_rating.unique()

array(['R', 'PG-13', 'NOT RATED', 'PG', 'UNRATED', 'APPROVED', 'PASSED',
       'G', 'X', nan, 'TV-MA', 'GP', 'NC-17'], dtype=object)

In [7]:
m1['genre'].unique()

array(['Crime', 'Action', 'Drama', 'Western', 'Adventure', 'Biography',
       'Comedy', 'Animation', 'Mystery', 'Horror', 'Film-Noir', 'Sci-Fi',
       'History', 'Thriller', 'Family', 'Fantasy'], dtype=object)

In [8]:
m1.genre.nunique()

16

In [9]:
m1.genre.value_counts()

Drama        278
Comedy       156
Action       136
Crime        124
Biography     77
Adventure     75
Animation     62
Horror        29
Mystery       16
Western        9
Sci-Fi         5
Thriller       5
Film-Noir      3
Family         2
Fantasy        1
History        1
Name: genre, dtype: int64

In [10]:
m1.actors_list[0]

"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunton']"

In [11]:
m1[(m1.genre=='Drama') & (m1.duration>200)]

,star_rating,title,content_rating,genre,duration,actors_list
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."

In [12]:
m1.title.str.upper().head()

0    THE SHAWSHANK REDEMPTION
1               THE GODFATHER
2      THE GODFATHER: PART II
3             THE DARK KNIGHT
4                PULP FICTION
Name: title, dtype: object

In [13]:
m1[m1.title.str.contains('godfather', case=False)]

,star_rating,title,content_rating,genre,duration,actors_list
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
711,7.6,The Godfather: Part III,R,Crime,162,"[u'Al Pacino', u'Diane Keaton', u'Andy Garcia']"

In [14]:
m1[m1.title.str.contains('Dark',case=False)]

,star_rating,title,content_rating,genre,duration,actors_list
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
43,8.5,The Dark Knight Rises,PG-13,Action,165,"[u'Christian Bale', u'Tom Hardy', u'Anne Hatha..."
218,8.1,Donnie Darko,R,Drama,113,"[u'Jake Gyllenhaal', u'Jena Malone', u'Mary Mc..."
324,8.0,Dancer in the Dark,R,Crime,140,"[u'Bj\xf6rk', u'Catherine Deneuve', u'David Mo..."
488,7.8,Star Trek Into Darkness,PG-13,Action,132,"[u'Chris Pine', u'Zachary Quinto', u'Zoe Salda..."
583,7.8,Dark City,R,Mystery,100,"[u'Rufus Sewell', u'Kiefer Sutherland', u'Jenn..."
738,7.6,Army of Darkness,R,Comedy,81,"[u'Bruce Campbell', u'Embeth Davidtz', u'Marcu..."
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."

In [15]:
m1[m1.star_rating.between(8,9)]

,star_rating,title,content_rating,genre,duration,actors_list
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
9,8.9,Fight Club,R,Drama,139,"[u'Brad Pitt', u'Edward Norton', u'Helena Bonh..."
10,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
13,8.8,Forrest Gump,PG-13,Drama,142,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']"
14,8.8,The Lord of the Rings: The Two Towers,PG-13,Adventure,179,"[u'Elijah Wood', u'Ian McKellen', u'Viggo Mort..."
15,8.7,Interstellar,PG-13,Adventure,169,"[u'Matthew McConaughey', u'Anne Hathaway', u'J..."
16,8.7,One Flew Over the Cuckoo's Nest,R,Drama,133,"[u'Jack Nicholson', u'Louise Fletcher', u'Mich..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
18,8.7,Goodfellas,R,Biography,146,"[u'Robert De Niro', u'Ray Liotta', u'Joe Pesci']"
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
20,8.7,The Matrix,R,Action,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
21,8.7,City of God,R,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
22,8.7,It's a Wonderful Life,APPROVED,Drama,130,"[u'James Stewart', u'Donna Reed', u'Lionel Bar..."
23,8.7,The Usual Suspects,R,Crime,106,"[u'Kevin Spacey', u'Gabriel Byrne', u'Chazz Pa..."
24,8.7,Se7en,R,Drama,127,"[u'Morgan Freeman', u'Brad Pitt', u'Kevin Spac..."
25,8.6,Life Is Beautiful,PG-13,Comedy,116,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G..."
26,8.6,Once Upon a Time in the West,PG-13,Western,175,"[u'Henry Fonda', u'Charles Bronson', u'Claudia..."
27,8.6,The Silence of the Lambs,R,Drama,118,"[u'Jodie Foster', u'Anthony Hopkins', u'Lawren..."
28,8.6,Leon: The Professional,R,Crime,110,"[u'Jean Reno', u'Gary Oldman', u'Natalie Portm..."
29,8.6,City Lights,PASSED,Comedy,87,"[u'Charles Chaplin', u'Virginia Cherrill', u'F..."
30,8.6,Spirited Away,PG,Animation,125,"[u'Daveigh Chase', u'Suzanne Pleshette', u'Miy..."
31,8.6,The Intouchables,R,Biography,112,"[u'Fran\xe7ois Cluzet', u'Omar Sy', u'Anne Le ..."
32,8.6,Casablanca,PG,Drama,102,"[u'Humphrey Bogart', u'Ingrid Bergman', u'Paul..."
...,...,...,...,...,...,...
364,8.0,Rosemary's Baby,R,Drama,136,"[u'Mia Farrow', u'John Cassavetes', u'Ruth Gor..."
365,8.0,Mystic River,R,Crime,138,"[u'Sean Penn', u'Tim Robbins', u'Kevin Bacon']"
366,8.0,Serenity,PG-13,Action,119,"[u'Nathan Fillion', u'Gina Torres', u'Chiwetel..."
367,8.0,Amarcord,R,Comedy,123,"[u'Magali No\xebl', u'Bruno Zanin', u'Pupella ..."
368,8.0,Planet of the Apes,G,Adventure,112,"[u'Charlton Heston', u'Roddy McDowall', u'Kim ..."
369,8.0,True Romance,R,Crime,120,"[u'Christian Slater', u'Patricia Arquette', u'..."
370,8.0,Hannah and Her Sisters,PG-13,Comedy,103,"[u'Mia Farrow', u'Dianne Wiest', u'Michael Cai..."
371,8.0,Moon,R,Drama,97,"[u'Sam Rockwell', u'Kevin Spacey', u'Dominique..."
372,8.0,Before Midnight,R,Drama,109,"[u'Ethan Hawke', u'Julie Delpy', u'Seamus Dave..."
373,8.0,My Name Is Khan,PG-13,Drama,165,"[u'Shah Rukh Khan', u'Kajol', u'Sheetal Menon']"
374,8.0,Scent of a Woman,R,Drama,156,"[u'Al Pacino', u""Chris O'Donnell"", u'James Reb..."
375,8.0,Mulholland Dr.,R,Drama,147,"[u'Naomi Watts', u'Laura Harring', u'Justin Th..."
376,8.0,King Kong,UNRATED,Adventure,100,"[u'Fay Wray', u'Robert Armstrong', u'Bruce Cab..."
377,8.0,The Fault in Our Stars,PG-13,Drama,126,"[u'Shailene Woodley', u'Ansel Elgort', u'Nat W..."
378,8.0,The Incredibles,PG,Animation,115,"[u'Craig T. Nelson', u'Samuel L. Jackson', u'H..."
379,8.0,Edward Scissorhands,PG-13,Drama,105,"[u'Johnny Depp', u'Winona Ryder', u'Dianne Wie..."
380,8.0,Casino Royale,PG-13,Action,144,"[u'Daniel Craig', u'Eva Green', u'Judi Dench']"
381,8.0,How to Train Your Dragon 2,PG,Animation,102,"[u'Jay Baruchel', u'Cate Blanchett', u'Gerard ..."
382,8.0,In Bruges,R,Comedy,107,"[u'Colin Farrell', u'Brendan Gleeson', u'Ciar\..."
383,8.0,The Untouchables,R,Crime,119,"[u'Kevin Costner', u'Sean Connery', u'Robert D..."
384,8.0,Breathless,UNRATED,Crime,90,"[u'Jean-Paul Belmondo', u'Jean Seberg', u'Dani..."
385,8.0,Spartacus,PG-13,Action,197,"[u'Kirk Douglas', u'Laurence Olivier', u'Jean ..."
386,8.0,The Iron Giant,PG,Animation,86,"[u'Eli Marienthal', u'Harry Connick Jr.', u'Je..."
387,8.0,Midnight Cowboy,X,Drama,113,"[u'Dustin Hoffman', u'Jon Voight', u'Sylvia Mi..."
388,8.0,The Blues Brothers,R,Action,133,"[u'John Belushi', u'Dan Aykroyd', u'Cab Callow..."
389,8.0,Freaks,UNRATED,Drama,64,"[u'Wallace Ford', u'Leila Hyams', u'Olga Bacla..."
390,8.0,Letters from Iwo Jima,R,Drama,141,"[u'Ken Watanabe', u'Kazunari Ninomiya', u'Tsuy..."
391,8.0,Edge of Tomorrow,PG-13,Action,113,"[u'Tom Cruise', u'Emily Blunt', u'Bill Paxton']"
392,8.0,Glory,R,Drama,122,"[u'Matthew Broderick', u'Denzel Washington', u..."
393,8.0,The African Queen,PG,Adventure,105,"[u'Humphrey Bogart', u'Katharine Hepburn', u'R..."

In [16]:
m1[m1.star_rating.between(8,9)].count()

star_rating       391
title             391
content_rating    390
genre             391
duration          391
actors_list       391
dtype: int64

In [17]:
m1.star_rating.max()

9.3

In [18]:
m1.star_rating.aggregate(['min','max','mean'])

min     7.400000
max     9.300000
mean    7.889785
Name: star_rating, dtype: float64

In [19]:
m1.isnull().sum()

star_rating       0
title             0
content_rating    3
genre             0
duration          0
actors_list       0
dtype: int64

In [20]:
#Top 5 movies with longest duration displaying title and duration as a DataFrame
m2=m1.sort_values('duration',ascending=False)[:5]
m2[['title','duration']]

                                 title  duration
476                             Hamlet       242
157                 Gone with the Wind       238
78         Once Upon a Time in America       229
142  Lagaan: Once Upon a Time in India       224
445               The Ten Commandments       220